name: chemcomp2.5
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter_core=5.8
  - conda=25.7
  - mamba=2.2
  - jupyterlab=4.4
  - nbclassic=1.3
  - notebook=7.4
  - traitlets=5.14
  - ase=3.28
  - beautifulsoup4=4.13
  - bokeh=3.9
  - cloudpickle=3.1
  - cython=3.2
  - dask=2026.3
  - dill=0.4
  - ffmpeg=8.0
  - gemmi=0.7
  - h5py=3.16
  - hdf5=1.14
  - ipympl=0.10
  - ipywidgets=8.1
  - lmfit=1.3
  - matplotlib-base=3.10
  - mdanalysis=2.10
  - nbconvert
  - nglview
  - numba=0.65
  - numexpr=2.14
  - numpy=2.4
  - patsy=1.0
  - protobuf=6.31
  - pymatgen=2026.5
  - pythreejs=2.4
  - pytest=9.0
  - pybind11=2.13
  - qcelemental=0.29
  - qcengine=0.31
  - scikit-image=0.26
  - scikit-learn=1.8
  - scipy=1.17
  - seaborn=0.13
  - sqlalchemy=2.0
  - statsmodels=0.14
  - sympy=1.14
  - xlrd=2.0
  - py-cpuinfo=9.0
  - nbgitpuller=1.3
  - rdkit=2024.03
  - voila=0.5
  - bqplot=0.13
  - mdtraj=1.11
  - py3dmol=2.5
  - cartopy=0.25
  - openbabel=3.1
  - openmm=8.5
  - libint=2.13
  - boost
  - pydantic=2.11
  - networkx=3.6
  - pint=0.25
  - msgpack-python=1.1
  - mpfr=4.2
  - eigen=5.0
  - pingouin=0.6
  - nbmake=1.5
  - opt_einsum=3.4
  - pip=25.2
  - imbalanced-learn=0.14
  - biopython=1.87
  - ipyevents=2.0
  - seqlike=1.5
  - vina=1.2
  - cclib=1.8
  - jupyterlab-git=0.53
  - pubchempy=1.0
  - transformers=5.9
  - langchain=1.3
  - langchain-openai=1.2
  - faiss-cpu=1.10
  - openai=2.38
  - chembl_webresource_client=0.10
  - pdb2pqr=3.6
  - prolif=2.1
  - pdbfixer=1.12
  - pandas=2.3
  - sweetviz=2.3
  - pillow=12.0
  - jupyterlab-myst=2.6
  - jupyter-resource-usage=1.2
  - geopandas=1.1
  - folium=0.20
  - contextily=1.7
  - pip:
    - adme-py==0.1.0
    - algebra-with-sympy==1.1.3
    - cachetools==7.1.4
    - colorlover==0.3.0
    - cufflinks==0.17.3
    - fair==2.2.4
    - flask==3.1.3
    - flask-wtf==1.3.0
    - fortecubeview==0.2.4
    - geometric==1.1.1
    - icn3dpy==3.49.0
    - idisplay==0.1.2
    - junit2html==31.1.3
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - meeko==0.7.1
    - moly==0.2.1
    - nmrglue==0.11
    - pandastools==0.2.3
    - pooch==1.9.0
    - purpleair==0.0.4
    - pyaermod==2.0.0
    - pynndescent==0.6.0
    - pyprind==2.11.3
    - rcsbsearchapi==1.6.0
    - sigfig==1.3.19
    - smilite==2.3.0
    - sympy-for-algebra==1.14.0
    - umap-learn==0.5.12
    - werkzeug==3.1.8
    - wtforms==3.2.2
    - xlsxwriter==3.2.9
    - pyodesys==0.14.7
    - chempy==0.10.1
